### ISSUE TITLE
When I was training, how to solve the error, the error is as follows:

### ISSUE THREAD

**Issue by tzl1** [leftthomas/SuperResolution#22]
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at c:\programdata\miniconda3\conda-bld\pytorch_1532505617613\work\aten\src\thc\generic/THCTensorMathPointwise.cu:59
  0%|          | 0/261 [00:23<?, ?it/s]

**Comment by leftthomas** [comment]
@tzl1 this is your cuda error, not the repo code error.

**Comment by tzl1** [comment]
The problem has been solved, but a new one has come up:Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x000001B2B3182EF0>>
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "E:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "E:\Anaconda3\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "E:\Anaconda3\lib\site-packages\torch\multiprocessing\reductions.py", line 167, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: Couldn't open shared event: <torch_876_3862243872_event>, error code: <2>
 39%|███▊      | 101/261 [11:13<17:47,  6.67s/it]

**Comment by leftthomas** [comment]
@tzl1 you should first search that by yourself to solve these problems, not just ask someone to solve that for you, and this problem also not belong to my repo code error.
