### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by shuyongzhang** [leftthomas/SuperResolution#23]
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

**Comment by leftthomas** [comment]
@shuyongzhang it has said "Use Tensor.cpu() to copy the tensor to host memory first"

**Comment by shuyongzhang** [comment]
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    engine.train(processor, train_loader, maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchnet\engine\engine.py", line 63, in train
    state['optimizer'].step(closure)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 51, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\adam.py", line 58, in step
    loss = closure()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchnet\engine\engine.py", line 56, in closure
    self.hook('on_forward', state)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchnet\engine\engine.py", line 31, in hook
    self.hooks[name](state)
  File "train.py", line 46, in on_forward
    meter_loss.add(state['loss'].data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchnet\meter\averagevaluemeter.py", line 29, in add
    self.std = np.sqrt(self.m_s / (self.n - 1.0))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\tensor.py", line 433, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by eeeeeei** [comment]
> TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

I also met this question recently, consider change the code:
" def on_forward(state):
    meter_psnr.add(state['output'].data, state['sample'][1])
    meter_loss.add(state['loss'].data[0]) 
"
to

"def on_forward(state):
     meter_psnr.add(state['output'].data.cpu(), state['sample'][1])
     meter_loss.add(state['loss'].data.cpu())
"
it works for me.
